
import java.awt.Color;
import java.awt.Font;
import static javafx.scene.input.KeyCode.X;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Emmanuel Ajayi
 */
public class NewJFrame extends javax.swing.JFrame {
private String start_game = "X";
private int xCount = 0;
private int oCount = 0;



    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }
    private void scores (){
    x_score.setText(String.valueOf(xCount));
    o_score.setText(String.valueOf(oCount));
    Font font1 = new Font( "Serif" , Font.BOLD, 44 );
    x_score.setFont(font1);
    o_score.setFont(font1);
    
    }
    private void player_chooser(){
        if (start_game.equalsIgnoreCase("X")){
            start_game = "O";
        
        }
        else {
            start_game = "X";
        
        }
        
    }
    private void to_win(){
    String b1 = jButton1.getText();
    String b2 = jButton2.getText();
    String b3 = jButton3.getText();
    String b5 = jButton5.getText();
    String b6 = jButton6.getText();
    String b7 = jButton7.getText();
    String b10 = jButton10.getText();
    String b11 = jButton11.getText();
    String b12 = jButton12.getText();
    if (b1== "X" &&b2 == "X" && b3 == "X" 
        ||b1== "X" &&b5 == "X" && b10 == "X"
         || b1== "X" &&b6 == "X" && b12 == "X" 
         || b5== "X" &&b6 == "X" && b7 == "X"
         || b10== "X" &&b11 == "X" && b12 == "X"
         || b10== "X" &&b6 == "X" && b3 == "X"
         || b12== "X" &&b7 == "X" && b3 == "X"
         || b2== "X" &&b6 == "X" && b11 == "X" ){
        JOptionPane.showMessageDialog(this,"Player X wins !", "Tic Tac Toe",JOptionPane.INFORMATION_MESSAGE);
        xCount++;
        scores();
        jButton1.setText(" ");
        jButton2.setText(" ");
        jButton3.setText(" ");
        jButton5.setText(" ");
        jButton6.setText(" ");
        jButton7.setText(" ");
        jButton10.setText(" ");
        jButton11.setText(" ");
        jButton12.setText(" ");
        
             
                
                
              
        
    
    }
      if (b1== "O" &&b2 == "O" && b3 == "O" 
        ||b1== "O" &&b5 == "O" && b10 == "O"
         || b1== "O" &&b6 == "O" && b12 == "O" 
         || b5== "O" &&b6 == "O" && b7 == "O"
         || b10== "O" &&b11 == "O" && b12 == "O"
         || b10== "O" &&b6 == "O" && b3 == "O"
         || b12== "O" &&b7 == "O" && b3 == "O"
         || b2== "O" &&b6 == "O" && b11 == "O" ){
        JOptionPane.showMessageDialog(this,"Player O wins !", "Tic Tac Toe",JOptionPane.INFORMATION_MESSAGE);
        oCount++;
        scores();
        jButton1.setText(" ");
        jButton2.setText(" ");
        jButton3.setText(" ");
        jButton5.setText(" ");
        jButton6.setText(" ");
        jButton7.setText(" ");
        jButton10.setText(" ");
        jButton11.setText(" ");
        jButton12.setText(" ");

}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        x_score = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        o_score = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic Tac Toe");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("                      Tic  Tac  Toe");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new java.awt.GridLayout(3, 5, 2, 2));

        jButton1.setBackground(new java.awt.Color(0, 204, 255));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jButton2.setBackground(new java.awt.Color(0, 204, 255));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        jButton3.setBackground(new java.awt.Color(0, 204, 255));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Player X :");
        jPanel3.add(jLabel1);

        x_score.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(x_score);

        jButton5.setBackground(new java.awt.Color(0, 204, 255));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);

        jButton6.setBackground(new java.awt.Color(0, 204, 255));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);

        jButton7.setBackground(new java.awt.Color(0, 204, 255));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Player O :");
        jPanel3.add(jLabel4);

        o_score.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(o_score);

        jButton10.setBackground(new java.awt.Color(0, 204, 255));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10);

        jButton11.setBackground(new java.awt.Color(0, 204, 255));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11);

        jButton12.setBackground(new java.awt.Color(0, 204, 255));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton12);

        jButton13.setBackground(new java.awt.Color(0, 204, 255));
        jButton13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton13.setText("Reset");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton13);

        jButton14.setBackground(new java.awt.Color(0, 204, 255));
        jButton14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton14.setText("Exit");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private JFrame frame;
    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        frame = new JFrame("Exit") ;
        if (JOptionPane.showConfirmDialog( frame, "Are you sure you want to exit","Tic Tac Toe", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        
        {
        System.exit(0);
    }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jButton1.setText(start_game);
//        if(player_chooser == "X") grid[i][j] = 1
//        else grid[i][j] = -1
        
        if (start_game.equalsIgnoreCase("X")){
            jButton1.setForeground(Color.BLUE);
            Font font1 = new Font( "Serif" , Font.BOLD, 44 );
            jButton1.setFont(font1);
        
        }
        else {
            jButton1.setForeground(Color.RED);
            Font font1 = new Font( "Serif" , Font.BOLD, 44 );
            jButton1.setFont(font1);
        
        }
       player_chooser();
       to_win();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         jButton2.setText(start_game);
        
        if (start_game.equalsIgnoreCase("X")){
            jButton2.setForeground(Color.BLUE);
            Font font1 = new Font( "Serif" , Font.BOLD, 44 );
            jButton2.setFont(font1);
        
        }
        else {
            jButton2.setForeground(Color.RED);
            Font font1 = new Font( "Serif" , Font.BOLD, 44 );
            jButton2.setFont(font1);
        
        }
       player_chooser();
       to_win();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         jButton3.setText(start_game);
        
        if (start_game.equalsIgnoreCase("X")){
            jButton3.setForeground(Color.BLUE);
            Font font1 = new Font( "Serif" , Font.BOLD, 44 );
            jButton3.setFont(font1);
        
        }
        else {
            jButton3.setForeground(Color.RED);
            Font font1 = new Font( "Serif" , Font.BOLD, 44 );
            jButton3.setFont(font1);
        
        }
       player_chooser();
       to_win();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         jButton5.setText(start_game);
        
        if (start_game.equalsIgnoreCase("X")){
            jButton5.setForeground(Color.BLUE);
            Font font1 = new Font( "Serif" , Font.BOLD, 44 );
            jButton5.setFont(font1);
        
        }
        else {
            jButton5.setForeground(Color.RED);
            Font font1 = new Font( "Serif" , Font.BOLD, 44 );
            jButton5.setFont(font1);
        
        }
       player_chooser();
       to_win();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         jButton6.setText(start_game);
        
        if (start_game.equalsIgnoreCase("X")){
            jButton6.setForeground(Color.BLUE);
            Font font1 = new Font( "Serif" , Font.BOLD, 44 );
            jButton6.setFont(font1);
        
        }
        else {
            jButton6.setForeground(Color.RED);
            Font font1 = new Font( "Serif" , Font.BOLD, 44 );
            jButton6.setFont(font1);
        
        }
       player_chooser();
       to_win();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         jButton7.setText(start_game);
        
        if (start_game.equalsIgnoreCase("X")){
            jButton7.setForeground(Color.BLUE);
            Font font1 = new Font( "Serif" , Font.BOLD, 44 );
            jButton7.setFont(font1);
        
        }
        else {
            jButton7.setForeground(Color.RED);
            Font font1 = new Font( "Serif" , Font.BOLD, 44 );
            jButton7.setFont(font1);
        
        }
       player_chooser();
       to_win();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
         jButton10.setText(start_game);
        
        if (start_game.equalsIgnoreCase("X")){
            jButton10.setForeground(Color.BLUE);
            Font font1 = new Font( "Serif" , Font.BOLD, 44 );
            jButton10.setFont(font1);
        
        }
        else {
            jButton10.setForeground(Color.RED);
            Font font1 = new Font( "Serif" , Font.BOLD, 44 );
            jButton10.setFont(font1);
        
        }
       player_chooser();
       to_win();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
         jButton11.setText(start_game);
        
        if (start_game.equalsIgnoreCase("X")){
            jButton11.setForeground(Color.BLUE);
            Font font1 = new Font( "Serif" , Font.BOLD, 44 );
            jButton11.setFont(font1);
        
        }
        else {
            jButton11.setForeground(Color.RED);
            Font font1 = new Font( "Serif" , Font.BOLD, 44 );
            jButton11.setFont(font1);
        
        }
       player_chooser();
       to_win();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
         jButton12.setText(start_game);
        
        if (start_game.equalsIgnoreCase("X")){
            jButton12.setForeground(Color.BLUE);
            Font font1 = new Font( "Serif" , Font.BOLD, 44 );
            jButton12.setFont(font1);
        
        }
        else {
            jButton12.setForeground(Color.RED);
            Font font1 = new Font( "Serif" , Font.BOLD, 44 );
            jButton12.setFont(font1);
        
        }
       player_chooser();
       to_win();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
       if ( JOptionPane.showConfirmDialog(rootPane,"Are you sure you want to reset game" )==JOptionPane.YES_OPTION){
        jButton1.setText(null);
        jButton2.setText(null);
        jButton3.setText(null);
        jButton5.setText(null);
        jButton6.setText(null);
        jButton7.setText(null);
        jButton10.setText(null);
        jButton11.setText(null);
        jButton12.setText(null);
        o_score.setText("0");
        x_score.setText("0");
        xCount= 0;
        oCount = 0;
        Font font1 = new Font( "Serif" , Font.BOLD, 44 );
        x_score.setFont(font1);
        o_score.setFont(font1);
        
       }
        
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel o_score;
    private javax.swing.JLabel x_score;
    // End of variables declaration//GEN-END:variables
}
